### ISSUE TITLE
How to read the output binary file?

### ISSUE THREAD

**Issue by chjiao** [felipelouza/egsa#1]
Hi, what is the format of the output binary file, how to read them in C++/C? 
Also, I am curious how you deal with the read index for generalized suffix array. When there are many reads, the read index may cost a lot of memory.

**Comment by felipelouza** [comment]
Hi, the output file **.gesa** can be read using [`esa_read_gsa()`](https://github.com/felipelouza/egsa/blob/master/lib/esa.c#L61). Here is an example of such usage ([`check_gsa()`](https://github.com/felipelouza/egsa/blob/master/lib/utils.c#L298)). Alternatively, you can write your own procedure to read this struct [`t_GSA`](https://github.com/felipelouza/egsa/blob/master/lib/utils.h#L45) from the file.
The read index is computed during the internal memory phase ([`esa_write_all()`](https://github.com/felipelouza/egsa/blob/master/lib/esa.c#L265)). We also consider this memory cost when we partition the input.
