### ISSUE TITLE
add non binary output format

### ISSUE THREAD

**Issue by fcharras** [felipelouza/egsa#2]
I'd like to play with this library, but I'm not familiar with C, an example of how to export the results to a text format would be very helpful, so it can be easily interfaced with anything.

**Comment by felipelouza** [comment]
If you run ./egsa with -b option, it will create a output file .bwt with the BWT.
The GESA output an be accessed as we answered to @chjiao here: https://github.com/felipelouza/egsa/issues/1.
I hope this help you.
Best!
